### ISSUE TITLE
Error while creating a project using composer. 

### ISSUE THREAD

**Issue by SkyzohKey** [mako-framework/framework#207]
Hey guys, thanks for the awesome framework you made. I already used in many projects but today when I tried to setup a new one, I got a weird error...

## OS Informations
| **Key**              | Value                         |
|----------------------|-------------------------------|
| **OS**               | Linux 4.4.0-59-generic        |
| **Distribution**     | elementaryOS (Ubuntu based)   |
| **Architecture**     | x86_64                        |
| **PHP Version**      | `PHP 7.0.13-0ubuntu0.16.04.1` |
| **Composer Version** | `Composer 1.0.0-beta2`        |

## Backtrace
```bash
$ composer create-project mako/app forum-tfe            
Installing mako/app (5.1.0)
  - Installing mako/app (5.1.0)
    Downloading: 100%         

Created project in forum-tfe
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing psr/log (1.0.2)
    Downloading: 100%         

  - Installing monolog/monolog (1.22.0)
    Downloading: 100%         

  - Installing mako/framework (5.1.2)
    Downloading: 100%         

mako/app suggests installing mako/repl (A runtime developer console, interactive debugger and REPL for the Mako framework)
mako/app suggests installing mako/toolbar (A debug toolbar for the Mako framework)
monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
monolog/monolog suggests installing mongodb/mongodb (Allow sending log messages to a MongoDB server via PHP Driver)
monolog/monolog suggests installing php-amqplib/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
monolog/monolog suggests installing sentry/sentry (Allow sending log messages to a Sentry server)
Writing lock file
Generating autoload files
> php app/reactor app.generate_secret

Fatal error: Uncaught Error: Call to undefined function mako\application\mb_language() in /home/skyzohkey/Dev/php/forum-tfe/vendor/mako/framework/src/mako/application/Application.php:276
Stack trace:
#0 /home/skyzohkey/Dev/php/forum-tfe/vendor/mako/framework/src/mako/application/Application.php(490): mako\application\Application->configure()
#1 /home/skyzohkey/Dev/php/forum-tfe/vendor/mako/framework/src/mako/application/Application.php(88): mako\application\Application->boot()
#2 /home/skyzohkey/Dev/php/forum-tfe/vendor/mako/framework/src/mako/application/Application.php(105): mako\application\Application->__construct('/home/skyzohkey...')
#3 /home/skyzohkey/Dev/php/forum-tfe/app/reactor(13): mako\application\Application::start('/home/skyzohkey...')
#4 {main}
  thrown in /home/skyzohkey/Dev/php/forum-tfe/vendor/mako/framework/src/mako/application/Application.php on line 276
Script php app/reactor app.generate_secret handling the post-create-project-cmd event returned with an error

                      
  [RuntimeException]  
  Error Output:       
                      

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
```

**Comment by letr0n** [comment]
It seems like your system is missing the `mbstring` module.

You can check if you have it installed using the following snippet

```bash
php -m |grep mbstring
```

**Comment by SkyzohKey** [comment]
Oh, stupid me. Issue solved, thanks x')
