### ISSUE TITLE
Exception using Subqueries in Mako 8 Resultset

### ISSUE THREAD

**Issue by ossigeno** [mako-framework/framework#291]
###  Description
---
Upgrading an Mako 7 app to Mako 8, getting exceptions in resultsets when ORM query contains subqueries.
...

###  Steps to reproduce
---
Perform a query on a model with a subquery and then return resultset:

```
$cars = (new Car)->where('workflow', '=', Workflow::Published)
                              ->in('id', new Subquery(function($query)
                              {
                                  $query->table('videos')
                                              ->select(['car_id'])
                                              ->distinct()
                                              ->where('status', '=', VideoStatus::Complete);
                              }))
                             ->all();
```
=> throws 
ArgumentCountError
Too few arguments to function mako\database\midgard\Query::__construct()

```
$cars = (new Car)->where('workflow', '=', Workflow::Published)
                              ->in('id', new Subquery(function($query)
                              {
                                  $query->table('videos')
                                              ->select(['car_id'])
                                              ->distinct()
                                              ->where('status', '=', VideoStatus::Complete);
                              }));
```
=> return query alone works

```
$cars = (new Car)->where('workflow', '=', Workflow::Published)
                               ->all();
```
=> without subquery works
...

### Versions & Platform
---

| What         | Version                  |
|--------------|--------------------------|
| PHP Version  | 8.0.11                    |
| Mako Version | 8.0.1                  |
| OS           | MacOS Monterey                        |
| Database     | MariaDb                    |

**Comment by freost** [comment]
Hi,

Thanks. Do you have a stack trace as well?

**Comment by ossigeno** [comment]
```
[2021-12-02T20:48:57.577377+07:00] mako.ERROR: Too few arguments to function mako\database\midgard\Query::__construct(), 1 passed in /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/database/query/Query.php on line 210 and exactly 2 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function mako\\database\\midgard\\Query::__construct(), 1 passed in /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/database/query/Query.php on line 210 and exactly 2 expected at /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/database/midgard/Query.php:66)
[stacktrace]
#0 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/database/query/Query.php(210): mako\\database\\midgard\\Query->__construct(Object(mako\\database\\connections\\MySQL))
#1 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/database/query/compilers/Compiler.php(137): mako\\database\\query\\Query->newInstance()
#2 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/database/query/compilers/Compiler.php(665): mako\\database\\query\\compilers\\Compiler->subquery(Object(mako\\database\\query\\Subquery))
#3 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/database/query/compilers/Compiler.php(693): mako\\database\\query\\compilers\\Compiler->exists(Array)
#4 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/database/query/compilers/Compiler.php(714): mako\\database\\query\\compilers\\Compiler->whereConditions(Array)
#5 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/database/query/compilers/Compiler.php(905): mako\\database\\query\\compilers\\Compiler->wheres(Array)
#6 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/database/query/Query.php(1451): mako\\database\\query\\compilers\\Compiler->select()
#7 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/database/midgard/Query.php(534): mako\\database\\query\\Query->fetchAll(false, 2)
#8 /Users/Lester/Projects/mobildijual.id/app/controllers/Home.php(41): mako\\database\\midgard\\Query->all()
#9 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/syringe/Container.php(597): app\\controllers\\Home->index(Object(mako\\view\\ViewFactory), Object(mako\\http\
outing\\URLBuilder))
#10 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/http/routing/Dispatcher.php(290): mako\\syringe\\Container->call(Array, Array)
#11 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/http/routing/Dispatcher.php(326): mako\\http\
outing\\Dispatcher->executeController(Object(app\\controllers\\Home), Array)
#12 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/http/routing/Dispatcher.php(341): mako\\http\
outing\\Dispatcher->executeAction(Object(mako\\http\
outing\\Route))
#13 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/onion/Onion.php(125): mako\\http\
outing\\Dispatcher->mako\\http\
outing\\{closure}(Object(mako\\http\\Request), Object(mako\\http\\Response))
#14 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/onion/Onion.php(201): mako\\onion\\Onion->mako\\onion\\{closure}(Object(mako\\http\\Request), Object(mako\\http\\Response))
#15 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/http/routing/Dispatcher.php(341): mako\\onion\\Onion->peel(Object(Closure), Array)
#16 /Users/Lester/Projects/mobildijual.id/vendor/mako/framework/src/mako/application/web/Application.php(50): mako\\http\
outing\\Dispatcher->dispatch(Object(mako\\http\
outing\\Route))
#17 /Users/Lester/Projects/mobildijual.id/public/index.php(15): mako\\application\\web\\Application->run()
#18 {main}
","user":{"ip_address":"127.0.0.1"}} 
```

**Comment by freost** [comment]
Thanks, I have tagget a release with a fix.
